version: "3"
services:
  jupyter:
    build: .
    volumes:
      - ./input:/kaggle/input
      - ./working:/kaggle/working
      - ./template:/kaggle/template
      - ./tool:/kaggle/tool
      - ../library:/kaggle/library
      - ./setting.ini:/kaggle/setting.ini
      - ${HOME}/.kaggle/.env:/kaggle/.env
      - ${HOME}/.kaggle/kaggle.json:/root/.config/kaggle/kaggle.json
      
    working_dir: /kaggle
    ports:
      - 8889:8889
    command: jupyter notebook --port=8889 --ip=0.0.0.0 --allow-root
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
